### PR TITLE
Quit yarn

### PR DESCRIPTION
**Pull request by nukosuke**
Use package-lock.json instead of yarn.lock

---
This change is [Reviewable](https://reviewable.io/reviews/nukosuke/annict.js/82)

### CODE REVIEW

**Comment by wopian** [comment]
You can also get rid of Node 7 and 9 as they're unsupported

**Comment by nukosuke** [comment]
@wopian 
Thank you for your advise!
I think that Node 9 supports package-lock.json because it includes npm5 according to [this page](https://nodejs.org/ja/download/releases/).
It is supported by npm5 or later, right?

Did you mean Node 6 and 7?

**Comment by wopian** [comment]
@nukosuke https://github.com/nodejs/Release#end-of-life-releases

**Comment by nukosuke** [comment]
I fixed it.
Thanks!

**Pull request merged**
